### ISSUE TITLE
Act. 7; Línea de tiempo sobre la Web (1.0, 2.0 y 3.0), Emmanuel Marx Salazar González 1BS

### ISSUE THREAD

**Issue by marxgonzalez29** [SistemasTecTlaxiaco/actividad-7-marxgonzalez29#1]
![línea de tiempo-1](https://user-images.githubusercontent.com/112300981/196255222-ddee0399-5563-4455-8356-1dd426c74869.jpg)

**Comment by Jaczibeth** [comment]
del 20% obtuviste un 17%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
